### ISSUE TITLE
Sample large Excel file does not work

### ISSUE THREAD

**Issue by rabol** [TrudAX/XppTools#5]
The ImportFromExcelExampleLarge.xlsx

cannot be imported using the DEVReadFromFileExampleCreateJournal class - the columns does not match

**Comment by TrudAX** [comment]
Hi @rabol . Yes, this file(ImportFromExcelExampleLarge.xlsx) is for testing how to read the data, not for a journal creation
![image](https://user-images.githubusercontent.com/26786918/102285480-1bd25680-3f82-11eb-81bf-755a61d2354c.png)
You can add additional lines to ImportFromExcelExample.xlsx to test journal creation. 
Now also working on a new blog post regarding mass journal creation, so plan to provide additional examples in it. Thanks for the comments
