### ISSUE TITLE
DEVSysTableBrowser is not editable at UAT for 10.0.16 PU40

### ISSUE THREAD

**Issue by sa0479** [TrudAX/XppTools#6]
Hi Denis,

DEVSysTableBrowser seems not to be working at 10.0.16 PU40. Table Browser is not editable at UAT even if user is added to "Editable table browser" role.
Do you experience the same behaviour at 10.0.16 PU40 and higher?

**Comment by TrudAX** [comment]
Hi Sergey
I don't have access to UAT right now. I think this form should be just duplicated. Are you able to test if I give you a new form?

**Comment by sa0479** [comment]
Yes, Denis, I am able to test with a new form.

**Comment by TrudAX** [comment]
Hi Sergey, sorry for the delay. Can you please download the updated model https://github.com/TrudAX/XppTools/tree/master/DEVTools/DEVSysTableBrowser  and try. Thank

**Comment by sa0479** [comment]
Hi Denis! I've already duplicated SysTableBrowser class and form myself and tried at UAT - such approach works at UAT. If you use extension for SysTableBrowser class - this for some unknown reasons doesn't work at UAT. Probably system's core "blocks" extensions for some system classes.

**Comment by TrudAX** [comment]
Ok, great.
